server:
  port: 8086
spring:
  application:
    name: CONFIG-SERVER
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
